### ISSUE TITLE
CXX=C:\mingw530_32\bin\g++

### ISSUE THREAD

**Issue by NichtEuler** [beeond/opcua-modeling-tool#1]
What does this line in the makefile do?
I can't find a folder like this on my PC, even though I followed the instruction step by step(no g++ folder).
Help would be much appreciated.

**Comment by wentabat** [comment]
In the Compile umx section, the Makefile.**win**.properties(corrected from Makefile.**windows**.properties) should be configured based on your installation paths for MinGW-w64, wxWidgets, xerces and xsd.

![image](https://user-images.githubusercontent.com/4067221/38494390-623f9092-3bbb-11e8-93c1-f03e20b2208c.png)
